In [ ]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int) 

print(df)

# error: invalid Literal Thirty

In [4]:
# correct code:
import pandas as pd

data = {'Feature1': ['10', '20', '30'],
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int) 

print(df)

   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [8]:
# second way to remove converting the data to integer step
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)


print(df)

  Feature1  Feature2
0       10       5.5
1       20       6.7
2   Thirty       8.9


In [ ]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  
        'B': [4, None, 6]}  

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  
print(df)

# mean value is not modified in place of NA

In [12]:
# correct code
import pandas as pd

data = {'A': [1, 2, None],  
        'B': [4, None, 6]}  

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value, inplace=True)  
print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)
# ValueError: Expected 2D array, got 1D array instead

In [20]:
#3. correct code:
# reshape the 1D array to 2D array
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  
y = np.array([2, 4, 6, 8, 10])
X_reshaped = X.reshape(-1,1)
y_reshaped=y.reshape(-1,1)
model = LinearRegression()
model.fit(X_reshaped, y_reshaped)

LinearRegression()

In [ ]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]) 

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)
#ValueError: Expected 2D array, got 1D array instead:

In [26]:
#4.correct code
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]) 

data_reshaped = data.reshape(-1,1)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data_reshaped)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  
model = LogisticRegression()
model.fit(X, y)

In [68]:
#5.Correct code
#change the category values of y to  numeric labels
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1,0,1]  
model = LogisticRegression()
model.fit(X, y)
result=model.predict([[0,4]])
print(result)
# y labels should be numeric(encoded to numeric)

[1]


In [ ]:
#6.
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category']) 
print(encoded)


In [84]:

#6.correct code
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})



encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']])

print(encoded)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
#ValueError: Found input variables with inconsistent numbers of samples: [4, 3]


In [94]:
# correct code
# X and y should have same number of values 
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[5, 6], [1, 2], [7, 8]]
[[3, 4]]
[0, 0, 1]
[1]


In [ ]:
#7.
from sklearn.linear_model import LogisticRegression
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"] 
model = LogisticRegression()
model.fit(X_train, y_train)
# y_train should be conveted to labels(numeric values)

In [6]:
# correct code
from sklearn.linear_model import LogisticRegression
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [1,0,1] 
model = LogisticRegression()
model.fit(X_train, y_train)
result = model.predict([[3,6]])
print(result)

[1]


In [ ]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train)  
# ValueError: Input X contains NaN.

In [14]:
# correct code: replace the Nan values with mean values
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

df = pd.DataFrame(X_train)
mean_value = df.mean()
df.fillna(mean_value, inplace=True)  
print(X_train)

model = LinearRegression()
model.fit(X_train, y_train)  
result= model.predict([[1,3]])
print(result)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[12.5]


In [ ]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# categorical values should be converted to  numerical values for correct prediction

In [18]:
#9. correct code
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]  

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result=model.predict([[7,8]])
print(result)

[0]


In [ ]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]])) 
# For SVM, we should preprocess the input using StandardScaler to improve the model performance

In [26]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)
model = SVC()
model.fit(X_scaled, y_train)
result = print(model.predict([[1, 150]])) 

[0]
